from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    ("catalog", "0001_initial"),
  ]

  operations = [
    migrations.CreateModel(
      name="ThemeSetting",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("name", models.CharField(default="Default", max_length=80, unique=True)),
        ("tokens", models.JSONField(blank=True, default=dict)),
        ("is_active", models.BooleanField(default=True)),
      ],
    ),
    migrations.CreateModel(
      name="NavigationMenu",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("name", models.CharField(default="Primary", max_length=80, unique=True)),
        ("is_active", models.BooleanField(default=True)),
      ],
    ),
    migrations.CreateModel(
      name="FooterSetting",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("name", models.CharField(default="Default", max_length=80, unique=True)),
        ("about_text", models.TextField(blank=True)),
        ("chips", models.JSONField(blank=True, default=list)),
        ("bottom_left", models.CharField(blank=True, default="© 2026 GlowCare", max_length=140)),
        ("bottom_right", models.CharField(blank=True, default="Ctrl+Shift+A: admin mode (keyboard-only)", max_length=140)),
      ],
    ),
    migrations.CreateModel(
      name="AnnouncementBar",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("name", models.CharField(default="Primary", max_length=80, unique=True)),
        ("enabled", models.BooleanField(default=True)),
        ("badge", models.CharField(blank=True, max_length=40)),
        ("text", models.CharField(blank=True, max_length=160)),
        ("cta_text", models.CharField(blank=True, max_length=40)),
        ("cta_href", models.CharField(blank=True, max_length=240)),
        ("bg", models.CharField(blank=True, help_text="CSS background (optional)", max_length=160)),
        ("start_at", models.DateTimeField(blank=True, null=True)),
        ("end_at", models.DateTimeField(blank=True, null=True)),
      ],
    ),
    migrations.CreateModel(
      name="Homepage",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("name", models.CharField(default="Homepage", max_length=80, unique=True)),
        ("is_active", models.BooleanField(default=True)),
        ("announcement", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="homepages", to="cms.announcementbar")),
        ("footer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="homepages", to="cms.footersetting")),
        ("menu", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="homepages", to="cms.navigationmenu")),
        ("theme", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="homepages", to="cms.themesetting")),
      ],
    ),
    migrations.CreateModel(
      name="FooterColumn",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("title", models.CharField(max_length=50)),
        ("muted", models.CharField(blank=True, max_length=120)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("footer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="columns", to="cms.footersetting")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="FooterLink",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("label", models.CharField(max_length=80)),
        ("href", models.CharField(max_length=240)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("column", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links", to="cms.footercolumn")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="FooterSocialLink",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("label", models.CharField(max_length=10)),
        ("href", models.CharField(max_length=240)),
        ("aria_label", models.CharField(blank=True, max_length=60)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("column", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_links", to="cms.footercolumn")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="NavigationLink",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("label", models.CharField(max_length=40)),
        ("href", models.CharField(max_length=240)),
        ("is_pill", models.BooleanField(default=False)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("is_enabled", models.BooleanField(default=True)),
        ("menu", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links", to="cms.navigationmenu")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="HomepageSection",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("section_id", models.SlugField(max_length=40)),
        ("title", models.CharField(blank=True, max_length=80)),
        ("enabled", models.BooleanField(default=True)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("settings", models.JSONField(blank=True, default=dict)),
        ("homepage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="cms.homepage")),
      ],
      options={"ordering": ["sort_order", "id"], "unique_together": {("homepage", "section_id")}},
    ),
    migrations.CreateModel(
      name="HeroSlide",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("enabled", models.BooleanField(default=True)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("kicker", models.CharField(blank=True, max_length=90)),
        ("headline", models.CharField(blank=True, max_length=40)),
        ("headline2", models.CharField(blank=True, max_length=40)),
        ("sub", models.CharField(blank=True, max_length=220)),
        ("primary_label", models.CharField(blank=True, max_length=30)),
        ("primary_href", models.CharField(blank=True, max_length=240)),
        ("secondary_label", models.CharField(blank=True, max_length=30)),
        ("secondary_href", models.CharField(blank=True, max_length=240)),
        ("overlay_bg", models.CharField(blank=True, help_text="CSS overlay gradient/background for the slide", max_length=220)),
        ("button_styles", models.JSONField(blank=True, default=dict, help_text="Optional button style config")),
        ("ribbons", models.JSONField(blank=True, default=list)),
        ("meta", models.JSONField(blank=True, default=list)),
        ("background", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hero_backgrounds", to="catalog.mediaasset")),
        ("card_a", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hero_card_a", to="catalog.mediaasset")),
        ("card_b", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hero_card_b", to="catalog.mediaasset")),
        ("card_c", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hero_card_c", to="catalog.mediaasset")),
        ("homepage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hero_slides", to="cms.homepage")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="PromoStrip",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("enabled", models.BooleanField(default=True)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("title", models.CharField(max_length=70)),
        ("subtitle", models.CharField(blank=True, max_length=160)),
        ("pills", models.JSONField(blank=True, default=list)),
        ("button_label", models.CharField(blank=True, max_length=30)),
        ("button_href", models.CharField(blank=True, max_length=240)),
        ("bg", models.CharField(blank=True, help_text="CSS background override", max_length=220)),
        ("start_at", models.DateTimeField(blank=True, null=True)),
        ("end_at", models.DateTimeField(blank=True, null=True)),
        ("homepage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promo_strips", to="cms.homepage")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="AppBanner",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("enabled", models.BooleanField(default=True)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("title", models.CharField(max_length=70)),
        ("subtitle", models.CharField(blank=True, max_length=180)),
        ("stores", models.JSONField(blank=True, default=list)),
        ("bg", models.CharField(blank=True, help_text="CSS background override", max_length=220)),
        ("homepage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="app_banners", to="cms.homepage")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="FeaturedLogo",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("enabled", models.BooleanField(default=True)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("name", models.CharField(max_length=40)),
        ("homepage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="featured_logos", to="cms.homepage")),
        ("logo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="featured_logos", to="catalog.mediaasset")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="Testimonial",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("enabled", models.BooleanField(default=True)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("name", models.CharField(max_length=60)),
        ("meta", models.CharField(blank=True, max_length=80)),
        ("rating", models.DecimalField(decimal_places=2, default=5, max_digits=3)),
        ("text", models.TextField()),
        ("avatar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="testimonial_avatars", to="catalog.mediaasset")),
        ("homepage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="testimonials", to="cms.homepage")),
      ],
      options={"ordering": ["sort_order", "id"]},
    ),
    migrations.CreateModel(
      name="ProductSection",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("kind", models.CharField(choices=[("bestsellers", "Bestsellers"), ("newArrivals", "New arrivals"), ("skinConcerns", "Skin concerns")], max_length=30)),
        ("enabled", models.BooleanField(default=True)),
        ("sort_order", models.PositiveIntegerField(default=0)),
        ("title", models.CharField(max_length=60)),
        ("subtitle", models.CharField(blank=True, max_length=160)),
        ("view_all_href", models.CharField(blank=True, max_length=240)),
        ("tabs", models.JSONField(blank=True, default=list)),
        ("homepage", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_sections", to="cms.homepage")),
        ("pinned_products", models.ManyToManyField(blank=True, related_name="pinned_in_sections", to="catalog.product")),
      ],
      options={"ordering": ["sort_order", "id"], "unique_together": {("homepage", "kind")}},
    ),
  ]

